name: CI Pipeline

on:
  push:
    branches: [ "main", "ci-pipeline" ]
  pull_request:
    branches: [ "main", "ci-pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "🎉 Hello, GitHub Actions is working!"

